import type { Metadata } from "next";

import '../globals.css';
import { rubik } from "@/Shared/font/Rubik";
import Footer from "@/Shared/Foooter/footer";
import NavBar from "@/Shared/Navbar/NavBar";
import { SessionProvider } from "next-auth/react";
import TanstackProvider from "@/Shared/Providers/TanstackProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.className} antialiased`}
      >
        <SessionProvider>
          <TanstackProvider>
            <NavBar />
            {children}
            <Footer />
          </TanstackProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
