import type { Metadata } from "next";

import '../globals.css';
import { rubik } from "@/Shared/font/Rubik";
import Footer from "@/Shared/Foooter/footer";
import NavBar from "@/Shared/Navbar/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.className} antialiased`}
      >
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
