import type { Metadata } from "next";

import '../globals.css';
import { rubik } from "@/Shared/font/Rubik";
import { SessionProvider } from "next-auth/react";
import TanstackProvider from "@/Shared/Providers/TanstackProvider";
import { ChartBar, ChevronRight, CreditCard, Home, Menu, Package, Package2, Settings, Star, TicketPercent, Truck, Users2 } from "lucide-react";
import Link from "next/link";
import Dropdown from "@/Shared/Dropdown/DrowDown";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function DashboardLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${rubik.className} antialiased`}
            >
                <SessionProvider>
                    <TanstackProvider>
                        <div className="flex items-start h-dvh relative">
                            {/* Checkbox cachée pour contrôler l'état de la sidebar */}
                            <label htmlFor="sidebar-toggle" className="sr-only" >Sidebar Toggle</label>
                            <input type="checkbox" id="sidebar-toggle" className="hidden peer" defaultChecked />

                            {/* Sidebar */}
                            <aside className="w-[250px] bg-primary h-full transition-all duration-300 ease-in-out peer-checked:translate-x-0 -translate-x-full fixed left-0 top-0 z-10 overflow-y-auto scroll-bar">
                                <div className="p-4">
                                    <h1 className="global-h2 text-white text-2xl! text-center py-6">Decorva</h1>
                                    <nav className="flex flex-col gap-2 mt-2">
                                        <Link className=" hover:bg-[#6F9805] text-white p-2 rounded-sm transition-colors duration-200 flex items-center gap-3" href={'/'}>
                                            <Home className="w-4 h-4" />
                                            <span className="text-base leading-[110%]">Home</span>
                                        </Link>

                                        <Dropdown label="Products" icon={<Package className="w-4 h-4" />} items={[
                                            {
                                                label: "All Products",
                                                href: "/dashboard/products/all",
                                            },
                                            {
                                                label: "Add Product",
                                                href: "/dashboard/products/add",
                                            },
                                            {
                                                label: "Categories",
                                                href: "/dashboard/products/categories",
                                            },
                                            {
                                                label: "Attributes",
                                                href: "/dashboard/products/attributes",
                                            },
                                            {
                                                label: "Variations",
                                                href: "/dashboard/products/variations",
                                            },
                                            {
                                                label: "Inventory",
                                                href: "/dashboard/products/inventory",
                                            },
                                        ]} />

                                        <Dropdown label="Orders" icon={<Package2 className="w-4 h-4" />} items={[
                                            {
                                                label: "All Orders",
                                                href: "/dashboard/orders/all",
                                            },
                                            {
                                                label: "Pending",
                                                href: "/dashboard/orders/pending",
                                            },
                                            {
                                                label: "Processing",
                                                href: "/dashboard/orders/processing",
                                            },
                                            {
                                                label: "Shipped",
                                                href: "/dashboard/orders/shipped",
                                            },
                                            {
                                                label: "Completed",
                                                href: "/dashboard/orders/completed",
                                            },
                                            {
                                                label: "Cancelled / Returned",
                                                href: "/dashboard/orders/cancelled",
                                            },
                                        ]} />

                                        <Dropdown label="Customers" icon={<Users2 className="w-4 h-4" />} items={[
                                            {
                                                label: "All customers",
                                                href: "/dashboard/customers/all",
                                            },
                                            {
                                                label: "Customer details",
                                                href: "/dashboard/customers/details",
                                            },
                                            {
                                                label: "Order history",
                                                href: "/dashboard/orders/history",
                                            },
                                            {
                                                label: "Total spent",
                                                href: "/dashboard/orders/spent",
                                            },
                                            {
                                                label: "Last order date",
                                                href: "/dashboard/orders/last-order-date",
                                            },
                                        ]} />

                                        <Dropdown label="Coupons" icon={<TicketPercent className="w-4 h-4" />} items={[
                                            {
                                                label: "Active coupons",
                                                href: "/dashboard/coupons/active",
                                            },
                                            {
                                                label: "Expired coupons",
                                                href: "/dashboard/coupons/expired",
                                            },
                                            {
                                                label: "Create coupon",
                                                href: "/dashboard/coupons/create",
                                            },
                                        ]} />

                                        <Dropdown label="Shipping" icon={<Truck className="w-4 h-4" />} items={[
                                            {
                                                label: "Shipping Zones",
                                                href: "/dashboard/shipping/zones",
                                            },
                                            {
                                                label: "Shipping methods",
                                                href: "/dashboard/shipping/methods",
                                            },
                                            {
                                                label: "Rates",
                                                href: "/dashboard/shipping/rates",
                                            },
                                        ]} />

                                        <Dropdown label="Payments" icon={<CreditCard className="w-4 h-4" />} items={[
                                            {
                                                label: "Payment methods",
                                                href: "/dashboard/payments",
                                            },
                                            {
                                                label: "Transactions",
                                                href: "/dashboard/payments/transactions",
                                            },
                                            {
                                                label: "Failed payments",
                                                href: "/dashboard/payments/failed",
                                            },

                                        ]} />

                                        <Dropdown label="Reviews" icon={<Star fill="#ecc94b" className="w-4 h-4" />} items={[
                                            {
                                                label: "Pending approval",
                                                href: "/dashboard/reviews/pending",
                                            },
                                            {
                                                label: "Approved",
                                                href: "/dashboard/reviews/approved",
                                            },
                                            {
                                                label: "Spam",
                                                href: "/dashboard/reviews/spam",
                                            },
                                        ]} />

                                        <Dropdown label="Analytics" icon={<ChartBar className="w-4 h-4" />} items={[
                                            {
                                                label: "Sales report",
                                                href: "/dashboard/analytics/sales-report",
                                            },
                                            {
                                                label: "Product performance",
                                                href: "/dashboard/analytics/product-performance",
                                            },
                                            {
                                                label: "Customer analytics",
                                                href: "/dashboard/analytics/customer-analytics",
                                            },
                                        ]} />

                                        <Dropdown label="Settings" icon={<Settings className="w-4 h-4" />} items={[
                                            {
                                                label: "General",
                                                href: "/dashboard/settings/general",
                                            },
                                            {
                                                label: "Store info",
                                                href: "/dashboard/settings/store-info",
                                            },
                                            {
                                                label: "Taxes",
                                                href: "/dashboard/settings/taxes",
                                            },
                                            {
                                                label: "Shipping",
                                                href: "/dashboard/settings/shipping",
                                            },
                                            {
                                                label: "Payments",
                                                href: "/dashboard/settings/payments",
                                            },
                                            {
                                                label: "Roles & permissions",
                                                href: "/dashboard/settings/roles-permissions",
                                            }
                                        ]} />

                                    </nav>
                                </div>
                            </aside>

                            {/* Contenu principal */}
                            <main className="flex-1 h-full transition-all duration-300 ease-in-out peer-checked:ml-[250px] ml-0">
                                <label htmlFor="sidebar-toggle" className="cursor-pointer text-white font-bold text-xl inline-block hover:opacity-80 peer-checked:hidden w-full bg-blue-50 p-4">
                                    <Menu className="w-6 h-6 text-black" />
                                </label>
                                <div className="p-4">
                                    {children}
                                </div>
                            </main>
                        </div>
                    </TanstackProvider>
                </SessionProvider>
            </body>
        </html>
    );
}
