import type { Metadata } from "next";

import '../globals.css';
import { rubik } from "@/Shared/font/Rubik";
import { SessionProvider } from "next-auth/react";
import TanstackProvider from "@/Shared/Providers/TanstackProvider";
import { ChevronRight, Home, Menu, Package, Package2 } from "lucide-react";
import Link from "next/link";
import Dropdown from "@/Shared/Dropdown/DrowDown";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function DashboardLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${rubik.className} antialiased`}
            >
                <SessionProvider>
                    <TanstackProvider>
                        <div className="flex items-start h-dvh relative">
                            {/* Checkbox cachée pour contrôler l'état de la sidebar */}
                            <label htmlFor="sidebar-toggle" className="sr-only" >Sidebar Toggle</label>
                            <input type="checkbox" id="sidebar-toggle" className="hidden peer" defaultChecked />

                            {/* Sidebar */}
                            <aside className="w-[250px] bg-primary h-full transition-all duration-300 ease-in-out peer-checked:translate-x-0 -translate-x-full fixed left-0 top-0 z-10">
                                <div className="p-4">
                                    <h1 className="global-h2 text-white text-2xl! text-center py-6">Decorva</h1>
                                    <nav className="flex flex-col gap-2 mt-2">
                                        <Link className=" hover:bg-[#6F9805] text-white p-2 rounded-sm transition-colors duration-200 flex items-center gap-3" href={'/'}>
                                            <Home className="w-4 h-4" />
                                            <span className="text-base leading-[110%]">Home</span>
                                        </Link>


                                        <Dropdown label="Products" icon={<Package className="w-4 h-4" />} items={[
                                            {
                                                label: "All Products",
                                                href: "/products/all",
                                            },
                                            {
                                                label: "Add Product",
                                                href: "/products/add",
                                            },
                                        ]} />

                                        <Link className=" hover:bg-[#6F9805] text-white p-2 rounded-sm transition-colors duration-200 flex items-center justify-between gap-3" href={'/orders'}>
                                            <div className="flex items-center gap-3">
                                                <Package2 className="w-4 h-4" />
                                                <span className="text-base leading-[110%]">Orders</span>
                                            </div>
                                            <ChevronRight className="w-4 h-4" />
                                        </Link>
                                    </nav>
                                </div>
                            </aside>

                            {/* Contenu principal */}
                            <main className="flex-1 h-full transition-all duration-300 ease-in-out peer-checked:ml-[250px] ml-0">
                                <div className="p-4">
                                    <label htmlFor="sidebar-toggle" className="cursor-pointer text-white font-bold text-xl mb-4 inline-block hover:opacity-80 peer-checked:hidden">
                                        <Menu className="w-6 h-6 text-black" />
                                    </label>
                                    {children}
                                </div>
                            </main>
                        </div>
                    </TanstackProvider>
                </SessionProvider>
            </body>
        </html>
    );
}
