import type { Metadata } from "next";

import '../globals.css';
import { lora } from "@/Shared/font/Rubik";
import { SessionProvider } from "next-auth/react";
import TanstackProvider from "@/Shared/Providers/TanstackProvider";
import { Menu } from "lucide-react";
import SidebarNav from "@/Shared/Sidebar/SidebarNav";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function DashboardLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${lora.className} antialiased`}
            >
                <SessionProvider>
                    <TanstackProvider>
                        <div className="flex items-start h-dvh relative">
                            {/* Checkbox cachée pour contrôler l'état de la sidebar */}
                            <label htmlFor="sidebar-toggle" className="sr-only" >Sidebar Toggle</label>
                            <input type="checkbox" id="sidebar-toggle" className="hidden peer" defaultChecked />

                            {/* Sidebar */}
                            <aside className="w-[250px] bg-primary h-full transition-all duration-300 ease-in-out peer-checked:translate-x-0 -translate-x-full fixed left-0 top-0 z-10 overflow-y-auto scroll-bar">
                                <div className="p-4">
                                    <h1 className="global-h2 text-white text-2xl! text-center py-6">Decorva</h1>
                                    <SidebarNav />
                                </div>
                            </aside>

                            {/* Contenu principal */}
                            <main className="flex-1 h-full transition-all duration-300 ease-in-out peer-checked:ml-[250px] ml-0 bg-[#F0F0F1]">
                                <div className="p-4 bg-white w-full">
                                    <label htmlFor="sidebar-toggle" className="cursor-pointer text-white font-bold text-xl inline-block hover:opacity-80 peer-checked:hidden">
                                        <Menu className="w-6 h-6 text-black" />
                                    </label>
                                </div>
                                <div className="p-4">
                                    {children}
                                </div>
                            </main>
                        </div>
                    </TanstackProvider>
                </SessionProvider>
            </body>
        </html>
    );
}
